GoodsStore.WebUI/Controllers/AdminController.cs
using GoodsStore.BusinessLogic.Models;
using GoodsStore.BusinessLogic.Services.Interfaces;
using GoodsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GoodsStore.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        #region Fields
        private readonly IGoodsRepository _repository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IClothesTypeRepository _typeRepository;
        private readonly ISizeRepository _sizeRepository;
        private readonly IOrderRepository _orderRepository;
        private readonly IReviewRepository _reviewRepository;
        private int pageSize = 9;
        #endregion

        #region Constructor
        public AdminController(IGoodsRepository repository, ICategoryRepository categoryRepository,
            IClothesTypeRepository typeRepository, ISizeRepository sizeRepository,
            IOrderRepository orderRepository, IReviewRepository reviewRepository)
        {
            this._repository = repository;
            this._categoryRepository = categoryRepository;
            this._typeRepository = typeRepository;
            this._sizeRepository = sizeRepository;
            this._orderRepository = orderRepository;
            this._reviewRepository = reviewRepository;
        }
        #endregion

        #region Methods

        #region GoodsMethods
        public async Task<ActionResult> ListGoods(SearchGoods searchGoods, int page = 1)
        {
            ICollection<GoodsModel> goods = await this._repository.GetGoodsForOnePageAsync(searchGoods, pageSize, page);
            PagingInfo pageInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = await _repository.GetCountGoodsAsync(searchGoods)
            };
            GoodsListViewModel model = new GoodsListViewModel()
            {
                Goods = goods,
                PagingInfo = pageInfo,
                Search = searchGoods
            };

            return View(model);
        }
        public async Task<ActionResult> Goods(SearchGoods searchGoods, int page = 1)
        {
            ICollection<GoodsModel> goods = await this._repository.GetGoodsForOnePageAsync(searchGoods, pageSize, page);
            PagingInfo pageInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = await _repository.GetCountGoodsAsync(searchGoods)
            };
            GoodsListViewModel model = new GoodsListViewModel()
            {
                Goods = goods,
                PagingInfo = pageInfo,
                Search = searchGoods
            };

            return PartialView("_PartialAdmin_Goods",model);
        }

        [HttpGet]
        public async Task<ActionResult> EditGoods(int? goodsId)
        {
            if (goodsId != null)
            {
                GoodsModel goods = await this._repository.GetGoodsByIdAsync((int)goodsId);
                if (goods != null)
                {
                    ViewBag.Categories = new SelectList(await this._categoryRepository.GetCategoriesAsync(), "CategoryId", "Name");
                    ViewBag.ClothesTypes = new SelectList(await this._typeRepository.GetClothesTypesAsync(), "ClothesTypeId", "Name");
                    ViewBag.Sizes = await this._sizeRepository.GetSizesAsync();

                    return View(goods);
                }
                return RedirectToAction("ListGoods");
            }
            return HttpNotFound();
        }

        [HttpPost]
        public async Task<ActionResult> EditGoods(GoodsModel goods, int[] selectedSizes, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    goods.ImageData = new byte[image.ContentLength];
                    goods.ImageMimeType = image.ContentType;
                    image.InputStream.Read(goods.ImageData, 0, image.ContentLength);
                }
                if (goods.GoodsId == 0)
                {
                    await _repository.AddGoodsAsync(goods, selectedSizes);
                }
                else
                {
                    await _repository.SaveGoodsAsync(goods, selectedSizes);
                }
                TempData["message"] = string.Format("Изменения в товаре \"{0}\" были сохранены", goods.Name);
                return RedirectToAction("ListGoods");
            }
            else
            {
                ViewBag.Categories = new SelectList(await this._categoryRepository.GetCategoriesAsync(), "CategoryId", "Name");
                ViewBag.ClothesTypes = new SelectList(await this._typeRepository.GetClothesTypesAsync(), "ClothesTypeId", "Name");
                ViewBag.Sizes = await this._sizeRepository.GetSizesAsync();
                return View(goods);
            }
        }
        public async Task<ActionResult> AddGoods()
        {
            ViewBag.Categories = new SelectList(await this._categoryRepository.GetCategoriesAsync(), "CategoryId", "Name");
            ViewBag.ClothesTypes = new SelectList(await this._typeRepository.GetClothesTypesAsync(), "ClothesTypeId", "Name");
            ViewBag.Sizes = await this._sizeRepository.GetSizesAsync();

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> DeleteGoods(int goodsId)
        {
            GoodsModel deletedGoods = await this._repository.DeleteGoodsAsync(goodsId);
            if (deletedGoods != null)
            {
                TempData["message"] = string.Format("Товар \"{0}\" был удален!", deletedGoods.Name);
            }
            return RedirectToAction("ListGoods");
        }
        #endregion

        #region CategoryMethods
        public async Task<ActionResult> ListCategories(string searchName)
        {
            ICollection<CategoryModel> categories = await this._categoryRepository.GetCategoriesAsync(searchName);

            return View(categories);
        }

        [HttpGet]
        public async Task<ActionResult> EditCategory(int? categoryId)
        {
            if (categoryId != null)
            {
                CategoryModel category = await this._categoryRepository.GetCategoryByIdAsync((int)categoryId);
                if (category != null)
                {
                    return View(category);
                }
                return RedirectToAction("ListCategories");
            }

            return HttpNotFound();
        }

        [HttpPost]
        public async Task<ActionResult> EditCategory(CategoryModel category)
        {
            if (ModelState.IsValid)
            {
                await _categoryRepository.SaveCategoryAsync(category);

                TempData["message"] = string.Format("Изменения в категории \"{0}\" были сохранены", category.Name);
                return RedirectToAction("ListCategories");
            }
            else
            {
                return View(category);
            }
        }
        public ActionResult AddCategory(CategoryModel category)
        {
            return View("EditCategory", new CategoryModel());
        }

        [HttpPost]
        public async Task<ActionResult> DeleteCategory(int categoryId)
        {
            CategoryModel deletedCategory = await _categoryRepository.DeleteCategoryAsync(categoryId);
            if (deletedCategory != null)
            {
                TempData["message"] = string.Format("Категория \"{0}\" была удалена!", deletedCategory.Name);
            }
            return RedirectToAction("ListCategories");
        }
        #endregion

        #region ClothesTypeMethods
        public async Task<ActionResult> ListClothesTypes(string searchName)
        {
            ICollection<ClothesTypeModel> clothesTypes = await this._typeRepository.GetClothesTypesAsync(searchName);
            return View(clothesTypes);
        }

        [HttpGet]
        public async Task<ActionResult> EditClothesType(int? clothesTypeId)
        {
            if (clothesTypeId != null)
            {
                ClothesTypeModel clothesType = await this._typeRepository.GetClothesTypeByIdAsync((int)clothesTypeId);
                if (clothesType != null)
                {
                    return View(clothesType);
                }
                return RedirectToAction("ListClothesTypes");
            }
            return HttpNotFound();
        }

        [HttpPost]
        public async Task<ActionResult> EditClothesType(ClothesTypeModel clothesType)
        {
            if (ModelState.IsValid)
            {
                await this._typeRepository.SaveClothesTypeAsync(clothesType);

                TempData["message"] = string.Format("Изменения в типе одежды \"{0}\" были сохранены", clothesType.Name);
                return RedirectToAction("ListClothesTypes");
            }
            else
            {
                return View(clothesType);
            }
        }
        public ActionResult AddClothesType(ClothesTypeModel clothesType)
        {
            return View("EditClothesType", new ClothesTypeModel());
        }

        [HttpPost]
        public async Task<ActionResult> DeleteClothesType(int clothesTypeId)
        {
            ClothesTypeModel deletedClothesType = await this._typeRepository.DeleteClothesTypeAsync(clothesTypeId);
            if (deletedClothesType != null)
            {
                TempData["message"] = string.Format("Тип одежды \"{0}\" была удалена!", deletedClothesType.Name);
            }
            return RedirectToAction("ListClothesTypes");
        }
        #endregion

        #region SizeMethods
        public async Task<ActionResult> ListSizes(string searchName)
        {

GoodsStore.WebUI/Controllers/GoodsController.cs
using GoodsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using GoodsStore.BusinessLogic.Services.Interfaces;
using GoodsStore.BusinessLogic.Models;
using AutoMapper;

namespace GoodsStore.WebUI.Controllers
{
    public class GoodsController : Controller
    {
        #region Fields
        private readonly IGoodsRepository _repository;
        private readonly IReviewRepository _reviewRepository;
        private readonly ISizeRepository _sizeRepository;
        public int pageSize = 6;
        private int pageSizeForReviews = 2;
        #endregion

        #region Constructor
        public GoodsController(IGoodsRepository repository, IReviewRepository reviewRepository, ISizeRepository sizeRepository)
        {
            this._repository = repository;
            this._reviewRepository = reviewRepository;
            this._sizeRepository = sizeRepository;
        }
        #endregion

        #region Methods
        public async Task<ActionResult> Cards(SearchGoods search, int page = 1)
        {
            ICollection<GoodsModel> goods = await this._repository.GetGoodsForOnePageAsync(search, pageSize, page);

            PagingInfo pageInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = await _repository.GetCountGoodsAsync(search)
            };
            GoodsListViewModel model = new GoodsListViewModel()
            {
                Goods = goods,
                PagingInfo = pageInfo,
                Search = search
            };
            return PartialView("_PartialCards", model);
        }
        public async Task<ViewResult> GoodsCards(SearchGoods search, int page = 1)
        {
            ICollection<GoodsModel> goods = await this._repository.GetGoodsForOnePageAsync(search, pageSize, page);

            PagingInfo pageInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = await _repository.GetCountGoodsAsync(search)
            };
            GoodsListViewModel model = new GoodsListViewModel()
            {
                Goods = goods,
                PagingInfo = pageInfo,
                Search = search
            };
            return View(model);
        }
        public async Task<FileContentResult> GetImage(int? goodsId)
        {
            GoodsModel goods = await _repository.GetGoodsByIdAsync((int)goodsId);
            if (goods != null)
            {
                return File(goods.ImageData, goods.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public async Task<ActionResult> GetGoodsDescription(int? goodsId, int page = 1)
        {
            if (goodsId != null)
            {
                GoodsModel goods = await _repository.GetGoodsByIdAsync((int)goodsId);
                if (goods != null)
                {
                    ICollection<ReviewModel> reviews = await this._reviewRepository.GetReviewsByGoodsIdForOnePageAsync((int)goodsId, pageSizeForReviews, page);

                    PagingInfo pageInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSizeForReviews,
                        TotalItems = await this._reviewRepository.GetCountReviewsByGoodsIdAsync((int)goodsId)
                    };

                    ReviewsListViewModel model = new ReviewsListViewModel
                    {
                        Reviews = reviews,
                        PagingInfo = pageInfo,
                        Goods = goods,
                    };
                    return View(model);
                }
                else
                {
                    return new HttpNotFoundResult();
                }
            }
            else
            {
                return RedirectToAction("GoodsCards");
            }
        }
        [HttpGet]
        public async Task<ActionResult> ListReviews(int? goodsId, int page = 1)
        {
            if (goodsId != null)
            {
                ICollection<ReviewModel> reviews = await this._reviewRepository.GetReviewsByGoodsIdForOnePageAsync((int)goodsId, pageSizeForReviews, page);
                PagingInfo pageInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSizeForReviews,
                    TotalItems = await this._reviewRepository.GetCountReviewsByGoodsIdAsync((int)goodsId)
                };
                GoodsModel goods = await this._repository.GetGoodsByIdAsync((int)goodsId);
                ReviewsListViewModel model = new ReviewsListViewModel { Reviews = reviews, PagingInfo = pageInfo,Goods =goods };
                return PartialView("_PartialReviews", model);
            }
            return new HttpNotFoundResult();
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public async Task<ActionResult> AddReview(string comment, int goodsId, int rate)
        {
            if (comment!="" && rate > 0)
            {
                GoodsModel goods = await _repository.GetGoodsByIdAsync(goodsId);
                goods.Rating = Math.Round((goods.Rating * goods.NumberOfReviews + rate) / (goods.NumberOfReviews + 1), 1);
                goods.NumberOfReviews += 1;
                await _repository.UpdateRatingGoodsAsync(goods);

                if (goods != null)
                {
                    ReviewModel review = new ReviewModel();
                    review.GoodsId = goods.GoodsId;
                    review.Comment = comment;
                    review.UserName = User.Identity.GetUserName();
                    review.Rating = rate;
                    review.Date = DateTime.Now;
                    await _reviewRepository.SaveReviewAsync(review);
                }
            }
            return RedirectToAction("GetGoodsDescription", new { goodsId = goodsId });
        }
        #endregion
    }
}

GoodsStore.WebUI/Views/Nav/Menu.cshtml
@using GoodsStore.WebUI.Models
@model MenuListViewModel

@using (Ajax.BeginForm("Cards", "Goods",null, new AjaxOptions { UpdateTargetId = "listGoods_cards", HttpMethod = "get" }, new { @class = "navbar-form menu" }))
{ 
    <div class="form-group">
        <label class="control-label">Поиск по названию:</label><br />
        <input type="text" class="form-control" placeholder="Search" name="searchName" value="@Model.Search.searchName" /><br /><br />
        <label class="control-label">Тип одежды:</label><br />
        @foreach (var c in Model.ClothesTypes)
        {
            <label class="radio">
                <input type="radio" name="CurrentClothesType" value="@c.ClothesTypeId"
                       @(c.ClothesTypeId == Model.Search.CurrentClothesType ? "checked=\"checked\"" : "") />
                <span class="radio__text">@c.Name</span>
            </label><br />
        }
        <br /><label class="control-label">Категория: </label><br />
        @Html.DropDownList("CurrentCategory", Model.Categories as SelectList, "Please select",
                            htmlAttributes: new { @class = "form-control" })<br /><br />
        <label class="control-label">Размер: </label><br />
        @foreach (var s in Model.Sizes)
        { 
            <label class="radio">
                <input type="radio" name="CurrentSize" value="@s.SizeId"
                       @(s.SizeId == Model.Search.CurrentSize ? "checked=\"checked\"" : "") />
                <span class="radio__text">@s.Name</span>
            </label><br />
        }
        <br />
        <label class="control-label">Ценовой диапазон: </label><br />
        <input type="text" name="MinPrice" class="form-control price" placeholder="от" value="@Model.Search.MinPrice" />
        <input type="text" name="MaxPrice" class="form-control price" placeholder="до" value="@Model.Search.MaxPrice" /><br /><br />
        <a href="../Goods/GoodsCards" class="a_style">Сбросить настройки</a><br /><br />
        <button type="submit" class="btn btn-success form-control">Поиск</button>
    </div>
}

GoodsStore.WebUI/Views/Nav/MenuAdminForReviews.cshtml
@model GoodsStore.WebUI.Models.MenuForReviewListModel

@using (Ajax.BeginForm("Reviews", "Admin",null, new AjaxOptions { UpdateTargetId = "admin_body", HttpMethod = "get" }, new { @class = "navbar-form menu" }))
{
    <div class="form-group">
        <label class="control-label">Тип: </label>
        @Html.DropDownList("goodsId", Model.Goods as SelectList, "Выберите...",
                            htmlAttributes: new { @class = "form-control" })<br />
        <label class="control-label">Рейтинг: </label><br />
        <input type="text" name="rating" class="form-control" placeholder="Рейтинг" value="@Model.Search.rating"/><br /><br />
        <label class="control-label">Ник пользователя: </label><br />
        <input type="text" name="UserName" class="form-control" placeholder="Ник" value="@Model.Search.UserName"/><br /><br />
        <a href="ListReviews" class="a_style">Сбросить настройки</a><br /><br />
        <button type="submit" class="btn btn-success form-control">Поиск</button>
    </div>
}

GoodsStore.WebUI/Views/Nav/MenuForAdmin.cshtml
@using GoodsStore.WebUI.Models
@model MenuListViewModel

@using (Ajax.BeginForm("Goods", "Admin",null, new AjaxOptions { UpdateTargetId = "admin_body", HttpMethod = "get" }, new { @class = "navbar-form menu" }))
{
    <div class="form-group">
        <label class="control-label">Тип: </label><br />
        @foreach (var c in Model.ClothesTypes)
        {
            <label class="radio">
                <input type="radio" name="CurrentClothesType" value="@c.ClothesTypeId"
                       @(c.ClothesTypeId == Model.Search.CurrentClothesType ? "checked=\"checked\"" : "") />
                <span class="radio__text">@c.Name</span>
            </label><br />
        }
        <br /><label class="control-label">Категория: </label><br />
        @Html.DropDownList("CurrentCategory", Model.Categories as SelectList, "Выберите...",
                            htmlAttributes: new { @class = "form-control" })<br /><br />
        <a href="ListGoods" class="a_style">Сбросить настройки</a><br /><br />
        <button type="submit" class="btn btn-success form-control">Поиск</button>
    </div>
}