GoodsStore.WebUI/Controllers/CartController.cs
using GoodsStore.BusinessLogic.Models;
using GoodsStore.BusinessLogic.Services;
using GoodsStore.BusinessLogic.Services.Interfaces;
using GoodsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GoodsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        #region Fields
        private IGoodsRepository repository;
        private ISizeRepository sizeRepository;
        private IOrderProcessor orderProcessor;
        private IOrderRepository orderRepository;
        #endregion

        #region Constructor
        public CartController(IGoodsRepository repository, IOrderProcessor orderProcessor,
            IOrderRepository orderRepository,ISizeRepository sizeRepository)
        {
            this.repository = repository;
            this.sizeRepository = sizeRepository;
            this.orderProcessor = orderProcessor;
            this.orderRepository = orderRepository;
        }
        #endregion

        #region Methods
        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public async Task<RedirectToRouteResult> AddToCart(Cart cart,CartLineViewModel model)
        {
            if (model.sizeId != null)
            {
                GoodsModel goods = await this.repository.GetGoodsByIdAsync(model.goodsId);
                SizeModel size = await this.sizeRepository.GetSizeByIdAsync((int)model.sizeId);
                if (goods != null)
                {
                    cart.AddItem(goods,size, Convert.ToInt32(model.quantity));
                }
                return RedirectToAction("Index", new { model.returnUrl });
            }
            TempData["message"] = "Выберите размер";
            return RedirectToAction("GetGoodsDescription", "Goods", new { goodsId = model.goodsId });
        }

        public async Task<RedirectToRouteResult> RemoveFromCart(Cart cart,CartLineViewModel model)
        {
            GoodsModel goods = await this.repository.GetGoodsByIdAsync(model.goodsId);
            SizeModel size = await this.sizeRepository.GetSizeByIdAsync((int)model.sizeId);
            if (goods != null)
            {
                cart.RemoveLine(goods,size);
            }
            return RedirectToAction("Index", new { model.returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        [HttpGet]
        public ActionResult Checkout(Cart cart,string returnUrl)
        {
            if (cart.Lines.Count() == 0)
            {
                return RedirectToAction("Index", new { returnUrl });
            }
            return View(new OrderModel());
        }

        [HttpPost]
        public async Task<ViewResult> Checkout(Cart cart, OrderModel shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                await orderProcessor.ProcessOrder(cart, shippingDetails);
                await orderRepository.SaveOrderAsync(shippingDetails, cart.Lines);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        #endregion
    }
}

GoodsStore.WebUI/Controllers/GoodsController.cs
using GoodsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using GoodsStore.BusinessLogic.Services.Interfaces;
using GoodsStore.BusinessLogic.Models;
using AutoMapper;

namespace GoodsStore.WebUI.Controllers
{
    public class GoodsController : Controller
    {
        #region Fields
        private readonly IGoodsRepository _repository;
        private readonly IReviewRepository _reviewRepository;
        private readonly ISizeRepository _sizeRepository;
        public int pageSize = 6;
        private int pageSizeForReviews = 2;
        #endregion

        #region Constructor
        public GoodsController(IGoodsRepository repository, IReviewRepository reviewRepository, ISizeRepository sizeRepository)
        {
            this._repository = repository;
            this._reviewRepository = reviewRepository;
            this._sizeRepository = sizeRepository;
        }
        #endregion

        #region Methods
        public async Task<ActionResult> Cards(SearchGoods search, int page = 1)
        {
            ICollection<GoodsModel> goods = await this._repository.GetGoodsForOnePageAsync(search, pageSize, page);

            PagingInfo pageInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = await _repository.GetCountGoodsAsync(search)
            };
            GoodsListViewModel model = new GoodsListViewModel()
            {
                Goods = goods,
                PagingInfo = pageInfo,
                Search = search
            };
            return PartialView("_PartialCards", model);
        }
        public async Task<ViewResult> GoodsCards(SearchGoods search, int page = 1)
        {
            ICollection<GoodsModel> goods = await this._repository.GetGoodsForOnePageAsync(search, pageSize, page);

            PagingInfo pageInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = await _repository.GetCountGoodsAsync(search)
            };
            GoodsListViewModel model = new GoodsListViewModel()
            {
                Goods = goods,
                PagingInfo = pageInfo,
                Search = search
            };
            return View(model);
        }
        public async Task<FileContentResult> GetImage(int? goodsId)
        {
            GoodsModel goods = await _repository.GetGoodsByIdAsync((int)goodsId);
            if (goods != null)
            {
                return File(goods.ImageData, goods.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public async Task<ActionResult> GetGoodsDescription(int? goodsId, int page = 1)
        {
            if (goodsId != null)
            {
                GoodsModel goods = await _repository.GetGoodsByIdAsync((int)goodsId);
                if (goods != null)
                {
                    ICollection<ReviewModel> reviews = await this._reviewRepository.GetReviewsByGoodsIdForOnePageAsync((int)goodsId, pageSizeForReviews, page);

                    PagingInfo pageInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSizeForReviews,
                        TotalItems = await this._reviewRepository.GetCountReviewsByGoodsIdAsync((int)goodsId)
                    };

                    ReviewsListViewModel model = new ReviewsListViewModel
                    {
                        Reviews = reviews,
                        PagingInfo = pageInfo,
                        Goods = goods,
                    };
                    return View(model);
                }
                else
                {
                    return new HttpNotFoundResult();
                }
            }
            else
            {
                return RedirectToAction("GoodsCards");
            }
        }
        [HttpGet]
        public async Task<ActionResult> ListReviews(int? goodsId, int page = 1)
        {
            if (goodsId != null)
            {
                ICollection<ReviewModel> reviews = await this._reviewRepository.GetReviewsByGoodsIdForOnePageAsync((int)goodsId, pageSizeForReviews, page);
                PagingInfo pageInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSizeForReviews,
                    TotalItems = await this._reviewRepository.GetCountReviewsByGoodsIdAsync((int)goodsId)
                };
                GoodsModel goods = await this._repository.GetGoodsByIdAsync((int)goodsId);
                ReviewsListViewModel model = new ReviewsListViewModel { Reviews = reviews, PagingInfo = pageInfo,Goods =goods };
                return PartialView("_PartialReviews", model);
            }
            return new HttpNotFoundResult();
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public async Task<ActionResult> AddReview(string comment, int goodsId, int rate)
        {
            if (comment!="" && rate > 0)
            {
                GoodsModel goods = await _repository.GetGoodsByIdAsync(goodsId);
                goods.Rating = Math.Round((goods.Rating * goods.NumberOfReviews + rate) / (goods.NumberOfReviews + 1), 1);
                goods.NumberOfReviews += 1;
                await _repository.UpdateRatingGoodsAsync(goods);

                if (goods != null)
                {
                    ReviewModel review = new ReviewModel();
                    review.GoodsId = goods.GoodsId;
                    review.Comment = comment;
                    review.UserName = User.Identity.GetUserName();
                    review.Rating = rate;
                    review.Date = DateTime.Now;
                    await _reviewRepository.SaveReviewAsync(review);
                }
            }
            return RedirectToAction("GetGoodsDescription", new { goodsId = goodsId });
        }
        #endregion
    }
}

GoodsStore.WebUI/Controllers/NavController.cs
using GoodsStore.BusinessLogic.Models;
using GoodsStore.BusinessLogic.Services.Interfaces;
using GoodsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GoodsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        #region Fields
        private readonly IGoodsRepository _repository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IClothesTypeRepository _typesRepository;
        private readonly ISizeRepository _sizeRepository;
        #endregion

        #region Constructor
        public NavController(ICategoryRepository categoryRepository, IClothesTypeRepository typesRepository,
            ISizeRepository sizeRepository, IGoodsRepository repository)
        {
            this._categoryRepository = categoryRepository;
            this._typesRepository = typesRepository;
            this._sizeRepository = sizeRepository;
            this._repository = repository;
        }
        #endregion

        #region Methods
        public PartialViewResult Menu(SearchGoods searchGoods)
        {
            IEnumerable<CategoryModel> categories = this._categoryRepository.GetCategories();
            ICollection<ClothesTypeModel> clothesTypes = this._typesRepository.GetClothesTypes();
            ICollection<SizeModel> sizes = this._sizeRepository.GetSizes();

            MenuListViewModel mlvm = new MenuListViewModel
            {
                Categories = new SelectList(categories, "CategoryId", "Name"),
                ClothesTypes = clothesTypes,
                Sizes = sizes,
                Search = searchGoods
            };

            return PartialView(mlvm);
        }
        public PartialViewResult MenuForAdmin(SearchGoods searchGoods)
        {
            IEnumerable<CategoryModel> categories = this._categoryRepository.GetCategories();
            ICollection<ClothesTypeModel> clothesTypes = this._typesRepository.GetClothesTypes();

            MenuListViewModel mlvm = new MenuListViewModel
            {
                Categories = new SelectList(categories, "CategoryId", "Name"),
                ClothesTypes = clothesTypes,
                Search = searchGoods
            };

            return PartialView(mlvm);
        }

        public PartialViewResult MenuAdminForReviews(SearchReview search)
        {
            ICollection<GoodsModel> goods = this._repository.GetGoods();

            MenuForReviewListModel mrlm = new MenuForReviewListModel
            {
                Goods = new SelectList(goods, "GoodsId", "Name"),
                Search=search
            };
            return PartialView(mrlm);
        }
        #endregion
    }
}

GoodsStore.WebUI/Views/Goods/GetGoodsDescription.cshtml
@using GoodsStore.WebUI.Models
@using GoodsStore.WebUI.HTMLHelpers

@using GoodsStore.Domain.Entities
@model ReviewsListViewModel

@{
    ViewBag.Title = "Описание товара";
}
<div class="description">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-danger">@TempData["message"]</div>
    }
    <div class="description_head">
        <div class="description_left_body">
            <div class="description_for_image">
                @if (Model.Goods.ImageData == null)
                {
                    <div class="description_image">Нет картинки</div>
                }
                else
                {

                    <img src="@Url.Action("GetImage", "Goods", new { Model.Goods.GoodsId })" class="description_image magniflier" />
                }
            </div>
            <div class="description_reviews">
                @using (Ajax.BeginForm("ListReviews", new { goodsId = Model.Goods.GoodsId }, new AjaxOptions { UpdateTargetId = "review", HttpMethod = "get" }))
                {
                    <button type="submit" class="btn btn-primary" onclick="OpenCloseReviews()">
                        Отзывы
                        <span class="badge">
                            @Model.Goods.NumberOfReviews
                        </span>
                    </button>

                }
            </div>
        </div>
        <div class="description_right_body">
            <div class="description_description">
                <h3>@Model.Goods.Name</h3>
                <p>@Model.Goods.Description</p>
            </div>
            <div class="rating_body">
                <div class="rate_background">
                    <div class="rate_bar" style="width:@((Model.Goods.Rating*20)+"%");"></div>
                </div>
                <div class="rating">
                    @String.Format("{0:0.0}", Model.Goods.Rating)
                </div>
            </div>
            <div class="description_right_container">
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    <p>Цена:</p>
                    <h4>@Model.Goods.Price руб.</h4>
                    <p>Размеры:</p>
                    foreach (var s in Model.Goods.Sizes)
                    {
                        <div>
                            <label class="radio values">
                                <input type="radio" name="sizeId" value="@s.SizeId" />
                                <span class="radio__text">@s.Name</span>
                            </label>
                        </div>
                    }
                    <p>Количество:</p>
                    <input type="button" value="-" onclick="Decrease()" />
                    <input type="text" value="1" name="quantity" id="quantity" readonly />
                    <input type="button" value="+" onclick="Increase()" />
                    <input type="hidden" name="goodsId" value="@Model.Goods.GoodsId" /><br /><br />
                    <input type="submit" class="btn btn-primary" value="Добавить в корзину" />
                    <a href="GoodsCards" class="btn btn-success">Вернуться на главную</a>
                }
            </div>
        </div>
    </div>
    <div id="reviews" class="review_head" style="display:none">
        @using (Html.BeginForm("AddReview", "Goods", FormMethod.Post))
        {
            <input type="hidden" id="rate" name="rate" value="0">
            <input type="hidden" name="goodsId" value="@Model.Goods.GoodsId">
            <div class="review_add">
                <textarea name="comment" placeholder="Добавить отзыв"></textarea>
                <div class="review_add_stars">
                    <h5><b>Оценить:</b></h5>
                    <div class="rate_background" id="stars_container" onclick="set_rate();">
                        <div class="rate_bar" id="stars" style="width:0%;"></div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                </button>
            </div>
        }
        <div id="review">
        </div>    
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/ForImages.js")
}

GoodsStore.WebUI/Views/Goods/GoodsCards.cshtml
@using GoodsStore.WebUI.Models
@using GoodsStore.WebUI.HTMLHelpers
@model GoodsListViewModel

@{
    ViewBag.Title = "Товары";
}
<div class="listGoods_body">
    <div class="listGoods_menu">
        @Html.Action("Menu", "Nav")
    </div>
    <div class="listGoods_cards" id="listGoods_cards">
         @Html.Partial("_PartialCards", Model)
    </div>
  
</div>